"""
Pure-Python PDF Forensic Analyzer for TenantGuard AI.
No external dependencies required (uses zlib, re, datetime from standard library).
"""
import re
import zlib
from datetime import datetime
from typing import Dict, Any, List, Tuple
from .models import RedFlag, RiskSeverity


# Known suspicious PDF creators / generators
SUSPICIOUS_PRODUCERS = [
    # Image/Graphic editors (paystubs are generated by payroll systems, NOT graphic software)
    ("photoshop", "Adobe Photoshop (Image manipulation software)", RiskSeverity.CRITICAL),
    ("illustrator", "Adobe Illustrator (Vector design software)", RiskSeverity.CRITICAL),
    ("canva", "Canva (Graphic design template platform)", RiskSeverity.CRITICAL),
    ("gimp", "GIMP (Image editor)", RiskSeverity.CRITICAL),
    ("inkscape", "Inkscape (Vector graphic editor)", RiskSeverity.CRITICAL),
    
    # Online PDF editors / converters (often used to modify existing stubs)
    ("ilovepdf", "iLovePDF (Online PDF modification tool)", RiskSeverity.HIGH),
    ("pdfescape", "PDFescape (Online PDF editor)", RiskSeverity.HIGH),
    ("sejda", "Sejda PDF Editor (Online PDF modification tool)", RiskSeverity.HIGH),
    ("smallpdf", "Smallpdf (Online PDF editor)", RiskSeverity.HIGH),
    ("pdf2go", "PDF2Go (Online PDF converter/editor)", RiskSeverity.HIGH),
    ("sodapdf", "Soda PDF (Online PDF editor)", RiskSeverity.HIGH),
    ("pdffiller", "PDFfiller (Online form editor)", RiskSeverity.HIGH),
    ("wondershare", "Wondershare PDFelement", RiskSeverity.HIGH),
    ("foxit", "Foxit PhantomPDF / Editor", RiskSeverity.MEDIUM),
    ("nitro", "Nitro Pro PDF Editor", RiskSeverity.MEDIUM),
    
    # Known online fake paystub generator signatures
    ("thepaystubs", "ThePayStubs.com (Online fake paystub generator)", RiskSeverity.CRITICAL),
    ("paystubmaker", "PaystubMaker (Online template generator)", RiskSeverity.CRITICAL),
    ("stubcheck", "StubCheck (Online stub generator)", RiskSeverity.CRITICAL),
    ("realcheckstubs", "RealCheckStubs (Online stub generator)", RiskSeverity.CRITICAL),
    ("fakepaystub", "FakePaystub generator footprint", RiskSeverity.CRITICAL),
    ("formcheck", "Online payroll form generator footprint", RiskSeverity.HIGH),
]

# Legitimate enterprise payroll software producers for trust benchmarking
LEGIT_PAYROLL_SYSTEMS = [
    "adp", "paychex", "workday", "gusto", "intuit", "quickbooks", 
    "ceridian", "dayforce", "paycom", "paylocity", "rippling", 
    "oracle peopleSoft", "sap"
]


class PDFForensics:
    def __init__(self, file_bytes: bytes):
        self.raw_data = file_bytes
        self.metadata: Dict[str, str] = {}
        self.extracted_text = ""
        self.is_pdf = self.raw_data.startswith(b"%PDF-")
        self.eof_count = 0
        self.has_incremental_update = False
        
    def analyze(self) -> Tuple[List[RedFlag], List[str], Dict[str, Any], str]:
        red_flags: List[RedFlag] = []
        clean_signals: List[str] = []
        
        if not self.is_pdf:
            red_flags.append(RedFlag(
                code="INVALID_PDF_HEADER",
                severity=RiskSeverity.CRITICAL,
                category="METADATA",
                title="Invalid PDF Format",
                description="The submitted file does not start with a valid %PDF- magic header.",
                suggested_action="Request original digital PDF directly from applicant."
            ))
            return red_flags, clean_signals, {}, ""

        # 1. Check for Incremental Updates (Multiple %%EOF or /Prev xref entries)
        self.eof_count = len(re.findall(rb"%%EOF", self.raw_data))
        has_prev_xref = bool(re.search(rb"/Prev\s+\d+", self.raw_data))
        
        if self.eof_count > 1 or has_prev_xref:
            self.has_incremental_update = True
            red_flags.append(RedFlag(
                code="PDF_INCREMENTAL_UPDATE_DETECTED",
                severity=RiskSeverity.HIGH,
                category="METADATA",
                title="Post-Creation PDF Alteration (Incremental Update)",
                description=(
                    f"File contains {self.eof_count} %%EOF revisions. "
                    "This indicates the document was modified and re-saved in an editor "
                    "after its initial creation."
                ),
                evidence={"eof_count": self.eof_count, "has_prev_xref": has_prev_xref},
                suggested_action="Ask tenant for a direct bank-generated or payroll-portal export."
            ))
        else:
            clean_signals.append("PDF structure shows a single revision (no post-export append detected).")

        # 2. Extract Metadata from /Info or XMP packets
        self.metadata = self._extract_metadata()
        
        creator = self.metadata.get("Creator", "")
        producer = self.metadata.get("Producer", "")
        combined_tools = f"{creator} {producer}".lower()
        
        # 3. Check for Suspicious Producers / Editors
        flagged_generator = False
        for keyword, label, severity in SUSPICIOUS_PRODUCERS:
            if keyword in combined_tools:
                flagged_generator = True
                red_flags.append(RedFlag(
                    code=f"SUSPICIOUS_SOFTWARE_{keyword.upper()}",
                    severity=severity,
                    category="METADATA",
                    title=f"Suspicious Software Footprint: {label}",
                    description=(
                        f"Document was created or edited with '{label}'. "
                        "Legitimate employers generate paystubs via automated enterprise payroll software, "
                        "not design suites or consumer PDF tools."
                    ),
                    evidence={"creator": creator, "producer": producer, "flagged_tool": label},
                    suggested_action="Reject this document. Require W-2 or bank direct-deposit connection."
                ))
                break
                
        if not flagged_generator:
            # Check if it matches known payroll systems
            matched_legit = [s for s in LEGIT_PAYROLL_SYSTEMS if s in combined_tools]
            if matched_legit:
                clean_signals.append(f"Producer metadata matches known payroll software ({matched_legit[0].upper()}).")
            else:
                clean_signals.append("No prohibited design/scam software signatures detected in metadata.")

        # 4. Check Date Anomalies (CreationDate vs ModDate)
        creation_date = self.metadata.get("CreationDate", "")
        mod_date = self.metadata.get("ModDate", "")
        
        c_dt = self._parse_pdf_date(creation_date)
        m_dt = self._parse_pdf_date(mod_date)
        
        if c_dt and m_dt:
            delta_seconds = abs((m_dt - c_dt).total_seconds())
            if delta_seconds > 300:  # modified more than 5 minutes after creation
                red_flags.append(RedFlag(
                    code="DATE_TAMPER_MODIFIED_AFTER_CREATION",
                    severity=RiskSeverity.HIGH,
                    category="METADATA",
                    title="Document Modified After Initial Generation",
                    description=(
                        f"Document was created on {c_dt.strftime('%Y-%m-%d %H:%M:%S')} "
                        f"but modified on {m_dt.strftime('%Y-%m-%d %H:%M:%S')} "
                        f"(Time delta: {int(delta_seconds / 3600)} hours). "
                        "Official payroll slips are immutable upon generation."
                    ),
                    evidence={"creation_date": str(c_dt), "mod_date": str(m_dt)},
                    suggested_action="Investigate why the payroll stub was edited days or hours later."
                ))
            else:
                clean_signals.append("Creation and modification timestamps are coherent.")

        # 5. Extract Text from PDF streams
        self.extracted_text = self._extract_text_streams()
        
        metadata_summary = {
            "creator": creator,
            "producer": producer,
            "creation_date": str(c_dt) if c_dt else creation_date,
            "mod_date": str(m_dt) if m_dt else mod_date,
            "revision_count": self.eof_count,
            "extracted_character_count": len(self.extracted_text)
        }
        
        return red_flags, clean_signals, metadata_summary, self.extracted_text

    def _extract_metadata(self) -> Dict[str, str]:
        meta = {}
        # Search for /Info << ... >>
        info_match = re.search(rb"/Info\s+(\d+)\s+(\d+)\s+R", self.raw_data)
        if info_match:
            obj_num = info_match.group(1)
            gen_num = info_match.group(2)
            # Find the object definition
            obj_pattern = rb"%s\s+%s\s+obj\s*<<(.*?)>>" % (obj_num, gen_num)
            obj_match = re.search(obj_pattern, self.raw_data, re.DOTALL)
            if obj_match:
                content = obj_match.group(1).decode("latin-1", errors="ignore")
                for key in ["Title", "Author", "Subject", "Creator", "Producer", "CreationDate", "ModDate"]:
                    m = re.search(r"/" + key + r"\s*\((.*?)\)", content, re.DOTALL)
                    if m:
                        meta[key] = m.group(1)
                    else:
                        # Hex string format <...>
                        m_hex = re.search(r"/" + key + r"\s*<([0-9a-fA-F]+)>", content)
                        if m_hex:
                            try:
                                meta[key] = bytes.fromhex(m_hex.group(1)).decode("utf-16-be", errors="ignore")
                            except Exception:
                                meta[key] = m_hex.group(1)

        # Fallback to direct regex across entire document
        for key in ["Creator", "Producer", "CreationDate", "ModDate"]:
            if key not in meta:
                direct = re.search(rb"/" + key.encode("latin-1") + rb"\s*\((.*?)\)", self.raw_data)
                if direct:
                    meta[key] = direct.group(1).decode("latin-1", errors="ignore")
                    
        return meta

    def _parse_pdf_date(self, date_str: str) -> Any:
        if not date_str:
            return None
        # PDF date format: D:YYYYMMDDHHmmSS...
        m = re.search(r"D:?(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})?", date_str)
        if m:
            year, month, day, hour, minute = int(m.group(1)), int(m.group(2)), int(m.group(3)), int(m.group(4)), int(m.group(5))
            sec = int(m.group(6)) if m.group(6) else 0
            try:
                return datetime(year, month, day, hour, minute, sec)
            except ValueError:
                return None
        return None

    def _extract_text_streams(self) -> str:
        extracted = []
        # Find all stream ... endstream blocks
        stream_matches = re.finditer(rb"<<(.*?)>>\s*stream\r?\n(.*?)\r?\nendstream", self.raw_data, re.DOTALL)
        for m in stream_matches:
            dict_header = m.group(1)
            stream_data = m.group(2)
            
            decompressed = None
            if b"/FlateDecode" in dict_header or b"/Fl" in dict_header:
                try:
                    decompressed = zlib.decompress(stream_data)
                except Exception:
                    try:
                        # Try without standard headers
                        decompressed = zlib.decompress(stream_data, -15)
                    except Exception:
                        pass
            else:
                decompressed = stream_data
                
            if decompressed:
                text_content = decompressed.decode("latin-1", errors="ignore")
                # Extract text within Tj or TJ operators
                # (Text) Tj
                tj_matches = re.findall(r"\((.*?)\)\s*Tj", text_content)
                extracted.extend(tj_matches)
                
                # [(T) 10 (e) 20 (xt)] TJ
                tj_array_matches = re.findall(r"\[(.*?)\]\s*TJ", text_content, re.DOTALL)
                for array_str in tj_array_matches:
                    inner_texts = re.findall(r"\((.*?)\)", array_str)
                    extracted.append("".join(inner_texts))

        return " ".join(extracted)
